base_url = "https://vnhnhm.github.io"
compile_sass = true
highlight_code = true
highlight_theme = "classic-modified"
build_search_index = true
theme = "even"
generate_rss = true
taxonomies = [
    {name = "about", rss = true},
    {name = "categories", rss = true},
]
title = "Sebastián Palma"

[extra]
katex_enable = true
katex_auto_render = true
even_title = "Sebastián Palma"